trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  BIT_CONFIG_USER_TOKEN: '<BIT CONFIG USER TOKEN>'
  GITHUB_TOKEN: 'GITHUB TOKEN'

steps:
- task: bit-init@0
- task: bit-dependency-update@0