trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  BIT_CONFIG_USER_TOKEN: '<BIT CONFIG USER TOKEN>'
  AZURE_DEVOPS_PAT: 'AZURE DEVOPS PAT'

steps:
- task: bit-init@0
- task: bit-dependency-update@0